// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blog.Entities;

#nullable disable

namespace blog.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20260608105141_flow_Defalt_Date")]
    partial class flow_Defalt_Date
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("blog.Entities.Blog.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("View")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("blog.Entities.Blog.PostsChangeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeRecord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int>("FK_PostsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("FK_PostsId");

                    b.ToTable("PostsChangeRecord");
                });

            modelBuilder.Entity("blog.Entities.Blog.PostsTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PostsTag");
                });

            modelBuilder.Entity("blog.Entities.Blog.PostsTagMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FK_PostsId")
                        .HasColumnType("int");

                    b.Property<int>("FK_TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_PostsId");

                    b.HasIndex("FK_TagId");

                    b.ToTable("PostsTagsMapping");
                });

            modelBuilder.Entity("blog.Entities.Files", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("blog.Entities.Flows.Flow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreateUser")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UpdateUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.HasIndex("UpdateUser");

                    b.ToTable("Flows");
                });

            modelBuilder.Entity("blog.Entities.Flows.FlowEdge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreateUser")
                        .HasColumnType("int");

                    b.Property<string>("DataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlowVersionId")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UpdateUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.HasIndex("FlowVersionId");

                    b.HasIndex("SourceNodeId");

                    b.HasIndex("TargetNodeId");

                    b.HasIndex("UpdateUser");

                    b.ToTable("FlowEdges");
                });

            modelBuilder.Entity("blog.Entities.Flows.FlowNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreateUser")
                        .HasColumnType("int");

                    b.Property<int>("FlowVersionId")
                        .HasColumnType("int");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UpdateUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.HasIndex("FlowVersionId");

                    b.HasIndex("UpdateUser");

                    b.ToTable("FlowNodes");
                });

            modelBuilder.Entity("blog.Entities.Flows.FlowRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FlowNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlowNodeId");

                    b.ToTable("FlowRules");
                });

            modelBuilder.Entity("blog.Entities.Flows.FlowVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreateUser")
                        .HasColumnType("int");

                    b.Property<int>("FlowId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UpdateUser")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.HasIndex("FlowId");

                    b.HasIndex("UpdateUser");

                    b.ToTable("FlowVersions");
                });

            modelBuilder.Entity("blog.Entities.Recipes.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("Complexity")
                        .HasColumnType("int");

                    b.Property<int>("CookingTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecipeDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeDetailId");

                    b.ToTable("RecipeDetail");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeDetailMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeDetailId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int?>("RecipeIngredientsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeDetailId");

                    b.HasIndex("RecipeId")
                        .IsUnique();

                    b.HasIndex("RecipeIngredientsId");

                    b.ToTable("RecipeDetailMapping");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeFileMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("RecipeId")
                        .IsUnique();

                    b.ToTable("RecipeFileMapping");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeIngredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IngredientsGroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeIngredientsDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IngredientsName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RecipeIngredientsDetail");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeIngredientsDetailMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeIngredientDetailId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeIngredientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeIngredientDetailId");

                    b.HasIndex("RecipeIngredientId");

                    b.ToTable("RecipeIngredientsDetailMapping");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeIngredientsMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeIngredientsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("RecipeIngredientsId");

                    b.ToTable("RecipeIngredientsMapping");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RecipeStep");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeStepMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("RecipeStepId");

                    b.ToTable("RecipeStepMapping");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RecipeTag");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeTagMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeTagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("RecipeTagId");

                    b.ToTable("RecipeTagMapping");
                });

            modelBuilder.Entity("blog.Entities.User.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("LogInDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("blog.Entities.Blog.Posts", b =>
                {
                    b.HasOne("blog.Entities.User.Users", "User")
                        .WithMany("Posts")
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("blog.Entities.Blog.PostsChangeRecord", b =>
                {
                    b.HasOne("blog.Entities.User.Users", "Users")
                        .WithMany("PostsChangeRecords")
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("blog.Entities.Blog.Posts", "Posts")
                        .WithMany("PostsChangeRecords")
                        .HasForeignKey("FK_PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("blog.Entities.Blog.PostsTagMapping", b =>
                {
                    b.HasOne("blog.Entities.Blog.Posts", "Posts")
                        .WithMany("PostsTagsMapping")
                        .HasForeignKey("FK_PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Entities.Blog.PostsTag", "PostsTag")
                        .WithMany("PostsTagMapping")
                        .HasForeignKey("FK_TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posts");

                    b.Navigation("PostsTag");
                });

            modelBuilder.Entity("blog.Entities.Flows.Flow", b =>
                {
                    b.HasOne("blog.Entities.User.Users", "CreateUsers")
                        .WithMany()
                        .HasForeignKey("CreateUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("blog.Entities.User.Users", "UpdateUsers")
                        .WithMany()
                        .HasForeignKey("UpdateUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreateUsers");

                    b.Navigation("UpdateUsers");
                });

            modelBuilder.Entity("blog.Entities.Flows.FlowEdge", b =>
                {
                    b.HasOne("blog.Entities.User.Users", "CreateUsers")
                        .WithMany()
                        .HasForeignKey("CreateUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("blog.Entities.Flows.FlowVersion", "FlowVersion")
                        .WithMany("FlowEdges")
                        .HasForeignKey("FlowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Entities.Flows.FlowNode", "FlowSourceNode")
                        .WithMany()
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("blog.Entities.Flows.FlowNode", "FlowTargetNode")
                        .WithMany()
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("blog.Entities.User.Users", "UpdateUsers")
                        .WithMany()
                        .HasForeignKey("UpdateUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreateUsers");

                    b.Navigation("FlowSourceNode");

                    b.Navigation("FlowTargetNode");

                    b.Navigation("FlowVersion");

                    b.Navigation("UpdateUsers");
                });

            modelBuilder.Entity("blog.Entities.Flows.FlowNode", b =>
                {
                    b.HasOne("blog.Entities.User.Users", "CreateUsers")
                        .WithMany()
                        .HasForeignKey("CreateUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("blog.Entities.Flows.FlowVersion", "FlowVersion")
                        .WithMany("FlowNodes")
                        .HasForeignKey("FlowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Entities.User.Users", "UpdateUsers")
                        .WithMany()
                        .HasForeignKey("UpdateUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreateUsers");

                    b.Navigation("FlowVersion");

                    b.Navigation("UpdateUsers");
                });

            modelBuilder.Entity("blog.Entities.Flows.FlowRule", b =>
                {
                    b.HasOne("blog.Entities.Flows.FlowNode", "FlowNode")
                        .WithMany("FlowRules")
                        .HasForeignKey("FlowNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowNode");
                });

            modelBuilder.Entity("blog.Entities.Flows.FlowVersion", b =>
                {
                    b.HasOne("blog.Entities.User.Users", "CreateUsers")
                        .WithMany()
                        .HasForeignKey("CreateUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("blog.Entities.Flows.Flow", "Flows")
                        .WithMany("FlowVersion")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Entities.User.Users", "UpdateUsers")
                        .WithMany()
                        .HasForeignKey("UpdateUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreateUsers");

                    b.Navigation("Flows");

                    b.Navigation("UpdateUsers");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeDetail", b =>
                {
                    b.HasOne("blog.Entities.Recipes.RecipeDetail", null)
                        .WithMany("RecipeDetails")
                        .HasForeignKey("RecipeDetailId");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeDetailMapping", b =>
                {
                    b.HasOne("blog.Entities.Recipes.RecipeDetail", "RecipeDetail")
                        .WithMany()
                        .HasForeignKey("RecipeDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Entities.Recipes.Recipe", "Recipe")
                        .WithOne("RecipeDetailMappings")
                        .HasForeignKey("blog.Entities.Recipes.RecipeDetailMapping", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Entities.Recipes.RecipeIngredients", null)
                        .WithMany("RecipeDetailMappings")
                        .HasForeignKey("RecipeIngredientsId");

                    b.Navigation("Recipe");

                    b.Navigation("RecipeDetail");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeFileMapping", b =>
                {
                    b.HasOne("blog.Entities.Files", "Files")
                        .WithOne("RecipeFileMapping")
                        .HasForeignKey("blog.Entities.Recipes.RecipeFileMapping", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Entities.Recipes.Recipe", "Recipe")
                        .WithOne("RecipeFileMappings")
                        .HasForeignKey("blog.Entities.Recipes.RecipeFileMapping", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Files");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeIngredientsDetailMapping", b =>
                {
                    b.HasOne("blog.Entities.Recipes.RecipeIngredientsDetail", "RecipeIngredientsDetail")
                        .WithMany("RecipeIngredientsDetailMappings")
                        .HasForeignKey("RecipeIngredientDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Entities.Recipes.RecipeIngredients", "RecipeIngredient")
                        .WithMany("RecipeIngredientsDetailMappings")
                        .HasForeignKey("RecipeIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeIngredient");

                    b.Navigation("RecipeIngredientsDetail");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeIngredientsMapping", b =>
                {
                    b.HasOne("blog.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeIngredientsMappings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Entities.Recipes.RecipeIngredients", "RecipeIngredients")
                        .WithMany("RecipeIngredientsMappings")
                        .HasForeignKey("RecipeIngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeStepMapping", b =>
                {
                    b.HasOne("blog.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeStepMappings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Entities.Recipes.RecipeStep", "RecipeStep")
                        .WithMany("RecipeStepMappings")
                        .HasForeignKey("RecipeStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("RecipeStep");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeTagMapping", b =>
                {
                    b.HasOne("blog.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeTagMappings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Entities.Recipes.RecipeTag", "RecipeTag")
                        .WithMany("RecipeTagMappings")
                        .HasForeignKey("RecipeTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("RecipeTag");
                });

            modelBuilder.Entity("blog.Entities.Blog.Posts", b =>
                {
                    b.Navigation("PostsChangeRecords");

                    b.Navigation("PostsTagsMapping");
                });

            modelBuilder.Entity("blog.Entities.Blog.PostsTag", b =>
                {
                    b.Navigation("PostsTagMapping");
                });

            modelBuilder.Entity("blog.Entities.Files", b =>
                {
                    b.Navigation("RecipeFileMapping")
                        .IsRequired();
                });

            modelBuilder.Entity("blog.Entities.Flows.Flow", b =>
                {
                    b.Navigation("FlowVersion");
                });

            modelBuilder.Entity("blog.Entities.Flows.FlowNode", b =>
                {
                    b.Navigation("FlowRules");
                });

            modelBuilder.Entity("blog.Entities.Flows.FlowVersion", b =>
                {
                    b.Navigation("FlowEdges");

                    b.Navigation("FlowNodes");
                });

            modelBuilder.Entity("blog.Entities.Recipes.Recipe", b =>
                {
                    b.Navigation("RecipeDetailMappings")
                        .IsRequired();

                    b.Navigation("RecipeFileMappings")
                        .IsRequired();

                    b.Navigation("RecipeIngredientsMappings");

                    b.Navigation("RecipeStepMappings");

                    b.Navigation("RecipeTagMappings");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeDetail", b =>
                {
                    b.Navigation("RecipeDetails");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeIngredients", b =>
                {
                    b.Navigation("RecipeDetailMappings");

                    b.Navigation("RecipeIngredientsDetailMappings");

                    b.Navigation("RecipeIngredientsMappings");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeIngredientsDetail", b =>
                {
                    b.Navigation("RecipeIngredientsDetailMappings");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeStep", b =>
                {
                    b.Navigation("RecipeStepMappings");
                });

            modelBuilder.Entity("blog.Entities.Recipes.RecipeTag", b =>
                {
                    b.Navigation("RecipeTagMappings");
                });

            modelBuilder.Entity("blog.Entities.User.Users", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("PostsChangeRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
