// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blog.Entities;

#nullable disable

namespace blog.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20260504033201_update_post")]
    partial class update_post
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("blog.Entities.Blog.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("View")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("blog.Entities.Blog.PostsChangeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeRecord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int>("FK_PostsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("FK_PostsId");

                    b.ToTable("PostsChangeRecord");
                });

            modelBuilder.Entity("blog.Entities.Blog.PostsTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PostsTag");
                });

            modelBuilder.Entity("blog.Entities.Blog.PostsTagMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FK_PostsId")
                        .HasColumnType("int");

                    b.Property<int>("FK_TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_PostsId");

                    b.HasIndex("FK_TagId");

                    b.ToTable("PostsTagsMapping");
                });

            modelBuilder.Entity("blog.Entities.User.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("LogInDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("blog.Entities.Blog.Posts", b =>
                {
                    b.HasOne("blog.Entities.User.Users", "User")
                        .WithMany("Posts")
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("blog.Entities.Blog.PostsChangeRecord", b =>
                {
                    b.HasOne("blog.Entities.User.Users", "Users")
                        .WithMany("PostsChangeRecords")
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("blog.Entities.Blog.Posts", "Posts")
                        .WithMany("PostsChangeRecords")
                        .HasForeignKey("FK_PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("blog.Entities.Blog.PostsTagMapping", b =>
                {
                    b.HasOne("blog.Entities.Blog.Posts", "Posts")
                        .WithMany("PostsTagsMapping")
                        .HasForeignKey("FK_PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Entities.Blog.PostsTag", "PostsTag")
                        .WithMany("PostsTagMapping")
                        .HasForeignKey("FK_TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posts");

                    b.Navigation("PostsTag");
                });

            modelBuilder.Entity("blog.Entities.Blog.Posts", b =>
                {
                    b.Navigation("PostsChangeRecords");

                    b.Navigation("PostsTagsMapping");
                });

            modelBuilder.Entity("blog.Entities.Blog.PostsTag", b =>
                {
                    b.Navigation("PostsTagMapping");
                });

            modelBuilder.Entity("blog.Entities.User.Users", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("PostsChangeRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
