name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blog

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Check format
        run: dotnet csharpier check .

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ../blog.Tests/blog.Tests.csproj --no-build --configuration Release --logger "console;verbosity=detailed"